version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    post_install:
      - python -m paquo get_qupath --install-path . 0.4.4
      - export PAQUO_QUPATH_DIR=${READTHEDOCS_REPOSITORY_PATH}/QuPath-0.4.4

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py